#!/usr/bin/env python

import robot_upstart
import os

j = robot_upstart.Job(name="roch-core", interface=os.environ.get('ROBOT_NETWORK'), workspace_setup=os.environ.get('ROBOT_SETUP'))

# Stuff to launch on system startup.
j.add(package="roch_base", glob="launch/*")

if os.path.exists('/dev/clearpath/imu'):
  j.add(package="roch_bringup", glob="launch/um6_config/*")

if os.path.exists('/dev/microstrain'):
  j.add(package="roch_bringup", glob="launch/microstrain_config/*")

if os.environ.get('roch_LMS1XX_IP'):
  j.add(package="husky_bringup", glob="launch/lms1xx_config/*")

j.install()
